remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: University of Jamestown - CDC Dept. 3D Printing Guide
description: Information on utilizing the 3D Printer(s) in the Computing, Design, and Communication Department at the University of Jamestown

show_downloads: false
